services:
  - type: web
    name: thetoolbox-website
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
