import {
  Settings,
  Cog,
  CircleDot,
  Zap,
  Shield,
  Wrench,
  Hammer,
  Drill,
  HardHat,
  Building2,
  Flame,
  Bolt,
} from 'lucide-react';

export const productsData = [
  {
    id: 1,
    title: 'Lincoln Automatic',
    category: 'Lubrication Systems',
    description: 'Advanced automatic lubrication systems for industrial machinery. Ensures optimal equipment performance and longevity through precise, automated lubrication delivery.',
    icon: Settings,
    image: 'https://images.pexels.com/photos/3862130/pexels-photo-3862130.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Automated delivery', 'Reduces downtime', 'Extends equipment life', 'Precise control'],
  },
  {
    id: 2,
    title: 'MAPRO Products',
    category: 'Industrial Solutions',
    description: 'Premium quality MAPRO industrial products and solutions. Comprehensive range of tools and equipment designed for demanding industrial applications.',
    icon: Cog,
    image: 'https://images.pexels.com/photos/257700/pexels-photo-257700.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Premium quality', 'Reliable performance', 'Industry tested', 'Wide selection'],
  },
  {
    id: 3,
    title: 'Bearings & Transmission',
    category: 'Mechanical Components',
    description: 'High-performance bearings and transmission products from leading manufacturers. Essential components for smooth and efficient machinery operation.',
    icon: CircleDot,
    image: 'https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['High durability', 'Low friction', 'Multiple sizes', 'Expert support'],
  },
  {
    id: 4,
    title: 'Diesel Generator Set',
    category: 'Power Generation',
    description: 'Reliable diesel generator sets for continuous power supply. Perfect for industrial facilities requiring dependable backup or primary power solutions.',
    icon: Zap,
    image: 'https://images.pexels.com/photos/162240/cables-cable-drum-large-162240.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['High efficiency', 'Fuel economy', 'Low emissions', 'Easy maintenance'],
  },
  {
    id: 5,
    title: 'Personal Protective Equipment',
    category: 'Safety Equipment',
    description: 'Complete range of safety equipment and PPE for worker protection. Meeting international safety standards to ensure workplace safety.',
    icon: Shield,
    image: 'https://images.pexels.com/photos/209235/pexels-photo-209235.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Certified safety', 'Comfortable fit', 'Durable materials', 'Full compliance'],
  },
  {
    id: 6,
    title: 'Electrical Tools & Accessories',
    category: 'Electrical Equipment',
    description: 'Professional electrical tools and accessories for installation and maintenance. Quality tools for electrical professionals and industrial applications.',
    icon: Bolt,
    image: 'https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Professional grade', 'Safety insulated', 'Precision tools', 'Complete sets'],
  },
  {
    id: 7,
    title: 'Hand Tools and Tackles',
    category: 'Manual Tools',
    description: 'Comprehensive selection of hand tools for various applications. Quality tools built to withstand demanding industrial use.',
    icon: Hammer,
    image: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Ergonomic design', 'Heavy-duty', 'Long-lasting', 'Wide variety'],
  },
  {
    id: 8,
    title: 'Lifting Tools',
    category: 'Material Handling',
    description: 'Heavy-duty lifting equipment and solutions for safe material handling. Essential equipment for construction and industrial lifting operations.',
    icon: Wrench,
    image: 'https://images.pexels.com/photos/236705/pexels-photo-236705.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['High capacity', 'Safety certified', 'Multiple options', 'Load tested'],
  },
  {
    id: 9,
    title: 'Construction Equipment',
    category: 'Construction',
    description: 'Professional construction tools and machinery for building projects. Reliable equipment designed to handle the toughest construction challenges.',
    icon: HardHat,
    image: 'https://images.pexels.com/photos/585419/pexels-photo-585419.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Professional grade', 'Rugged build', 'High performance', 'Service support'],
  },
  {
    id: 10,
    title: 'Structural Steel',
    category: 'Building Materials',
    description: 'Quality structural steel products for construction and fabrication. Meeting industry standards for strength and reliability.',
    icon: Building2,
    image: 'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['High strength', 'Quality certified', 'Various grades', 'Custom cutting'],
  },
  {
    id: 11,
    title: 'Welding Equipment',
    category: 'Welding',
    description: 'Complete welding equipment and consumables for all welding applications. Professional-grade welding solutions for industrial fabrication.',
    icon: Flame,
    image: 'https://images.pexels.com/photos/1267338/pexels-photo-1267338.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['All processes', 'Professional quality', 'Full accessories', 'Technical support'],
  },
  {
    id: 12,
    title: 'Power Tools & Abrasives',
    category: 'Power Equipment',
    description: 'Professional power tools and abrasive products for cutting, grinding, and finishing. High-performance tools for demanding applications.',
    icon: Drill,
    image: 'https://images.pexels.com/photos/5691577/pexels-photo-5691577.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['High power', 'Durable design', 'Variable speed', 'Complete range'],
  },
];

export const categories = [
  'All Products',
  'Lubrication Systems',
  'Industrial Solutions',
  'Mechanical Components',
  'Power Generation',
  'Safety Equipment',
  'Electrical Equipment',
  'Manual Tools',
  'Material Handling',
  'Construction',
  'Building Materials',
  'Welding',
  'Power Equipment',
];
